Repository TERITORI/teritori-dapp, pull requests merged in 2023-04, with the labels that each got.

#463 fix: Clickable "Upcoming Launches" cards #460 + updates to launchpad [👀]
  .graphqlconfig
  api/marketplace/v1/marketplace.proto
  go/internal/airtable_fetcher/upcoming.go
  go/internal/ethereum/ethereum.go
  go/internal/indexerdb/collection.go
  go/internal/indexerhandler/bunker_minter.go
  go/pkg/marketplace/marketplace_service.go
  go/pkg/marketplacepb/marketplace.pb.go
  go/pkg/thegraph/thegraph-schema.graphql
  go/pkg/thegraph/thegraph.go
  packages/api/marketplace/v1/marketplace.ts
  packages/components/CollectionView.tsx
  packages/components/TopMenu/TopMenuLiveMint.tsx
  packages/components/carousels/CarouselSection.tsx
  packages/components/carousels/CollectionsCarouselHeader.tsx
  packages/components/carousels/CollectionsCarouselSection.tsx
  packages/components/collections/CollectionGallery.tsx
  packages/screens/Launchpad/LaunchpadScreen.tsx
  schema.graphql
Labels: enhancement

#401 feat: dAppStore
  api/marketplace/v1/marketplace.proto
  assets/icons/dapp-store.svg
  assets/icons/greenCheck.svg
  assets/icons/random-goods-icon.svg
  assets/icons/warning-triangle-orange.svg
  assets/logos/Axelar-logo.svg
  assets/logos/artemisVision.png
  assets/logos/astroport.svg
  assets/logos/coinhall.svg
  assets/logos/daodao.png
  assets/logos/falconWallet.svg
  assets/logos/pulsar-logo.svg
  assets/logos/raydium.png
  assets/logos/sfoxy.png
  assets/logos/skip.png
  assets/logos/subdao.png
  assets/logos/theGraph.png
  assets/logos/toniPunks.png
  assets/logos/uniswap.png
  go.mod
  go.sum
  go/cmd/teritori-dapp-backend/main.go
  go/internal/airtable_fetcher/cache.go
  go/internal/airtable_fetcher/client.go
  go/internal/airtable_fetcher/dapps_store.go
  go/pkg/marketplace/marketplace_service.go
  go/pkg/marketplacepb/marketplace.pb.go
  go/pkg/marketplacepb/marketplace_grpc.pb.go
  package.json
  packages/api/marketplace/v1/marketplace.ts
  packages/components/BrandText/BrandText.tsx
  packages/components/BrandText/BrandTextBase.tsx
  packages/components/SVG/SVGorImageIcon.tsx
  packages/components/ScreenContainer.tsx
  packages/components/navigation/Navigator.tsx
  packages/components/navigation/Sidebar.tsx
  packages/components/navigation/components/SidebarButton.tsx
  packages/components/navigation/types.ts
  packages/components/sorts/SearchInput.tsx
  packages/screens/DAppStore/HomeScreen.tsx
  packages/screens/DAppStore/components/CheckboxDappStore.tsx
  packages/screens/DAppStore/components/DAppBox.tsx
  packages/screens/DAppStore/components/DAppStoreData.tsx
  packages/screens/DAppStore/components/Dropdown.tsx
  packages/screens/DAppStore/components/Header.tsx
  packages/screens/DAppStore/components/LeftRail.tsx
  packages/screens/DAppStore/components/RightRail.tsx
  packages/screens/DAppStore/components/SelectedDraggable.tsx
  packages/screens/DAppStore/query/util.ts
  packages/screens/DAppStore/types.ts
  packages/screens/RiotGame/component/RiotGameHeader.tsx
  packages/store/slices/dapps-store.ts
  packages/store/store.ts
  packages/utils/navigation.ts
  packages/utils/sidebar.ts
  yarn.lock
Labels: enhancement, dAppStore 🏬

#534 fix: reduce RPCs calls by disabling refetching
  packages/components/CollectionView.tsx
  packages/hooks/useCollectionInfo.ts
  packages/hooks/useCollections.ts
  packages/hooks/useMintEnded.ts
Labels: bug, enhancement

#547 fix(collection screen): better render during load
  packages/components/collections/CollectionHeader.tsx
Labels: bug

#546 feat: Make the Marketplace Landing page into a grid
  packages/components/OwnedNFTs.tsx
  packages/components/TopMenu/TopMenuLiveMint.tsx
  packages/components/carousels/CollectionsCarouselHeader.tsx
  packages/components/carousels/CollectionsCarouselSection.tsx
  packages/components/collections/CollectionGallery.tsx
  packages/hooks/useCollections.ts
  packages/screens/Marketplace/MarketplaceScreen.tsx
  packages/screens/RiotersFooter/RiotersFooterScreen.tsx
Labels: enhancement

#536 feat: use resizing image proxy for nfts and collections
  .env
  mainnet.env
  packages/components/CollectionView.tsx
  packages/components/ImageWithTextInsert.tsx
  packages/components/OptimizedImage.tsx
  packages/components/collections/CollectionInfoInline.tsx
Labels: enhancement
