Repository TERITORI/teritori-dapp, pull requests merged in 2023-03, with the labels that each got.

#471 Allow change pagination parameters Fix #470 [done ✅]
  packages/components/Pagination.tsx
  packages/components/activity/ActivityTable.tsx
Labels: bug, enhancement

#482 Allow Right click and Meta (control,command) open in a new tab [done ✅]
  packages/components/OmniLink.tsx
  packages/components/TopMenu/ConnectWalletButton.tsx
  packages/components/TopMenu/TopMenu.tsx
  packages/components/UserNameInline.tsx
  packages/components/collections/CollectionInfoInline.tsx
  packages/components/hub/ProfileButton.tsx
  packages/components/nfts/NFTView.tsx
  packages/screens/Marketplace/NFTDetailScreen.tsx
  packages/screens/UserPublicProfile/UserPublicProfileScreen.tsx
  packages/screens/WalletManager/MyNFTs.tsx
  packages/utils/setDocumentTitle.ts
Labels: bug

#472 Settings page [:shipit: ]
  .gitignore
  assets/icons/confirm.svg
  package.json
  packages/context/SidebarProvider.tsx
  packages/screens/Settings/SettingsScreen.tsx
  packages/screens/Settings/components/Notifications.tsx
  packages/screens/Settings/components/SettingItem.tsx
  packages/screens/Settings/components/UserProfileModal.tsx
  packages/screens/Settings/components/commonStyles.ts
  packages/screens/Settings/components/initProfile.ts
  packages/screens/Settings/types.ts
  packages/store/slices/settings.ts
  yarn.lock
Labels: enhancement

#493 fix: fix social feed navigation (and some UPP navigation)
  packages/components/TopMenu/TopMenuAccount.tsx
  packages/components/cards/CommentsContainer.tsx
  packages/components/navigation/components/SidebarProfileButton.tsx
  packages/components/socialFeed/NewsFeed/CreateShortPost/CreateShortPostModal.tsx
  packages/components/socialFeed/NewsFeed/NewsFeed.tsx
  packages/components/socialFeed/NewsFeed/NewsFeed.type.ts
  packages/components/socialFeed/NewsFeed/NewsFeedInput.tsx
  packages/components/socialFeed/RichText/RichText.web.tsx
  packages/components/socialFeed/SocialThread/SocialCardHeader.tsx
  packages/components/socialFeed/SocialThread/SocialCommentCard.tsx
  packages/components/socialFeed/SocialThread/SocialThreadCard.tsx
  packages/screens/FeedPostView/FeedPostViewScreen.tsx
  packages/utils/social-feed.ts
Labels: bug
